# Generated by Django 3.1.12 on 2021-09-15 15:21

# Note sure why but typing fails for `AddIndexConcurrently` here
from django.contrib.postgres.operations import AddIndexConcurrently  # type: ignore
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("posthog", "0167_feature_flag_override"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="event", index=models.Index(fields=["distinct_id"], name="posthog_eve_distinc_21c70a_idx"),
        ),
    ]
